---
rbac:
  install: true

Master:
  Image:    jenkins/jenkins
  ImageTag: 2.136
  ServiceType: ClusterIP
  HostName:    jenkins.cicd.do.citopro.com

  Ingress:
    Annotations:
      kubernetes.io/ingress.class: nginx

Persistence:
  Enabled: true
  StorageClass: standard
  Size: 2Gi